ENV_VAR_NAME_TOKEN_ISSUER_URL = 'TOKEN_ISSUER_URL'

PROJECT_RELATIVE_PATH_TO_ENVIRONMENT_FILE = '.env'

# region Data Model: Checker functions
CHECKER_ATTR_STATUS = 'status'
CHECKER_ATTR_TEXT = 'text'

CHECKER_MODEL_DATA_RETURN = {
    CHECKER_ATTR_TEXT: 'default',
    CHECKER_ATTR_STATUS: False
}
# endregion
